package com.rj.sync.model.original;

// Log represents a contract log event. These events are generated by the LOG opcode and
// stored/indexed by the node.
public class OriginalLog {
    // Consensus fields:
    // address of the contract that generated the event
    String address;
    // list of topics provided by the contract.
    String[] topics;
    // supplied by the contract, usually ABI-encoded
    byte[] data;

    // Derived fields. These fields are filled in by the node
    // but not secured by consensus.
    // block in which the transaction was included
    Long blockNumber;
    // hash of the transaction
    String txHash;
    // index of the transaction in the block
    Integer txIndex;
    // hash of the block in which the transaction was included
    String blockHash;
    // index of the log in the block
    Integer index;

    // The Removed field is true if this log was reverted due to a chain reorganisation.
    // You must pay attention to this field if you receive logs through a filter query.
    Boolean removed;
}
